pkgname=omen-fan-git
pkgver=r1.0000000
pkgrel=1
pkgdesc="Utility and daemon to control fans in HP Omen laptops"
arch=('any')
url="https://github.com/AksharLeo/omen-fan"
license=('GPL3')
depends=(
    'python'
    'python-click'
    'python-tomlkit'
    'python-click-aliases'
)
makedepends=('git')
backup=('etc/omen-fan/config.toml')

source=("git+$url.git")
sha256sums=('SKIP')

pkgver() {
    cd "$srcdir/omen-fan"
    printf "r%s.%s" \
        "$(git rev-list --count HEAD)" \
        "$(git rev-parse --short HEAD)"
}

package() {
    cd "$srcdir/omen-fan"

    # Install executables
    install -Dm755 omen-fan.py "$pkgdir/usr/bin/omen-fan"
    install -Dm755 omen-fand.py "$pkgdir/usr/bin/omen-fand"

    # Documentation
    install -Dm644 README.md \
        "$pkgdir/usr/share/doc/$pkgname/README.md"

    # Default configuration
    install -Dm644 /dev/stdin \
        "$pkgdir/etc/omen-fan/config.toml" <<'EOF'
# Generated by omen-fan-git

[service]
TEMP_CURVE = [45, 60, 70, 78, 84, 90]
SPEED_CURVE = [25, 40, 60, 75, 90, 100]
IDLE_SPEED = 20
POLL_INTERVAL = 5.0

[script]
BYPASS_DEVICE_CHECK = 1
EOF

    # systemd service
    install -Dm644 /dev/stdin \
        "$pkgdir/usr/lib/systemd/system/omen-fan.service" <<'EOF'
[Unit]
Description=HP Omen Fan Control Daemon
After=multi-user.target

[Service]
Type=forking
ExecStart=/usr/bin/omen-fan e start
ExecStop=/usr/bin/omen-fan e stop
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
}
